### ISSUE TITLE
cannot compile with gcc 4.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tst2005googlecode/mod-spdy#81]
```
What version/revision number of mod_spdy are you using?
0.9.4.1

What version of Apache are you using, and on what operating system?  (Use
`apache2ctl -v` to check.)
Server version: Apache/2.4.6 (Linux/SUSE)
OS: openSUSE 13.1

What other Apache modules are you using?  (Use `apache2ctl -M` to check.)


What browser version did you use to access the mod_spdy server?  On what
operating system? What flags was the browser invoked with?  (For
Chrome/Chromium, go to about:version to check.)


What steps will reproduce the problem?
1.try to compile mod-spdy with gcc 4.8

What is the expected result? What do you see instead?
I get the following error while compiling:

In file included from third_party/chromium/src/base/string16.h:33:0,
                 from third_party/chromium/src/base/string_piece_unittest.cc:7:
third_party/chromium/src/base/basictypes.h: In function 'Dest bit_cast(const 
Source&)':
third_party/chromium/src/base/basictypes.h:318:16: error: typedef 
'VerifySizesAreEqual' locally defined but not used 
[-Werror=unused-local-typedefs]
   typedef char VerifySizesAreEqual [sizeof(Dest) == sizeof(Source) ? 1 : -1];
                ^
cc1plus: all warnings being treated as errors
make: *** 
[out/Release/obj.target/base_unittests/third_party/chromium/src/base/string_piec
e_unittest.o] Error 1

```

Original issue reported on code.google.com by `witte...@gmail.com` on 30 Dec 2013 at 7:48
